// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exqhblzphtfpoutilali.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4cWhibHpwaHRmcG91dGlsYWxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2ODIwNjUsImV4cCI6MjA3NzI1ODA2NX0.CtJUfRTQrLZ98PucAqvdJr4IqCL8jYqu47bGU4sx07s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});